# Generated by Django 3.0.7 on 2020-06-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='is_acrtive',
            new_name='is_active',
        ),
    ]
