# Generated by Django 3.0.7 on 2020-06-15 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0002_auto_20200609_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('websites', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('wechat', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='flame.Store'),
        ),
    ]
