# Generated by Django 3.0.7 on 2020-06-19 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0003_auto_20200615_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_draft',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
