# Generated by Django 3.0.7 on 2020-06-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0004_auto_20200619_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ('-publish_time',)},
        ),
        migrations.AlterField(
            model_name='deal',
            name='is_draft',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='publish', max_length=10),
        ),
    ]
