# Generated by Django 3.0.7 on 2020-07-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0006_auto_20200627_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='tag',
            field=models.ManyToManyField(to='flame.Tag'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
