# Generated by Django 3.0.7 on 2020-08-07 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flame', '0007_auto_20200712_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='feature',
            field=models.CharField(choices=[('HotDeals', 'Hot Deals'), ('HuoOnly', 'Huozhezi Only'), ('GoodDeals', 'Good Deals')], default='GoodDeals', max_length=10),
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeimages', to='flame.Store')),
            ],
        ),
    ]
